version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Arshadpd/goa"